export const categoryData: Record<string, string[]> = {
  'jrpg': ['Final Fantasy Series', 'Chrono Trigger', 'Pokémon Series'],
  'ccg': ['Hearthstone', 'Magic Arena', 'Gwent'],
  'shooter': ['Call of Duty Series', 'DOOM Series'],
  'platformer': ['Mario Series', 'Earthworm Jim'],
  'arcade': ['Space Invaders', 'PacMan', 'Tetris'],
  'rts': ['Warcraft Series', 'Starcraft Series', 'Civilization Series'],
  'gacha': ['Genshin Impact', 'Honkai Star Rail'],
  'minis': ['Warcraft Rumble', 'Clash of Clans'],
  'puzzle': ['Legend of Zelda Series', 'Flow', 'Sudoku', 'Myst Series'],
  'weird': ['Katamari Damacy', 'Neko Atsume', 'Scribblenauts'],
  'party': ['Overcooked', 'Mario Party Series', 'Super Smash Brothers Series'],
  'music': ['Guitar Hero Series', 'Rock Band Series', 'Dance Dance Revolution Series'],
  'rogue': ['Slay the Spire', 'Roguebook'],
  'fighters': ['Mortal Kombat Series', 'Soul Calibur Series'],
  'superhero': ['Spiderman Series', 'Batman Series'],
  'mmo': ['World of Warcraft', 'Final Fantasy 14'],
};